export { VictoryModal } from './VictoryModal'
export { RulesModal } from './RulesModal'
export { ReplayModal } from './ReplayModal'
export { SettingsModal } from './SettingsModal'
export { RoomModal } from './RoomModal'
export { RankingModal } from './RankingModal'
